-- create Stage

CREATE OR REPLACE STAGE LOGISTICS_DB.BRONZE.RAW_STAGE
    DIRECTORY = (ENABLE = TRUE);    

CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.FILE_LOAD_AUDIT (
    LOAD_ID STRING,
    TABLE_NAME STRING,
    FILE_NAME STRING,
    ROW_COUNT NUMBER,
    LOAD_STATUS STRING,
    LOAD_START_TIME TIMESTAMP,
    LOAD_END_TIME TIMESTAMP,
    ERROR_MESSAGE STRING,
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);

-- Create Raw table 

CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,

    -- Ingestion Metadata
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);



CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_AMOUNT NUMBER(10,2),
    CITY STRING,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);


CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_PAYMENTS (
    PAYMENT_ID STRING,
    ORDER_ID STRING,
    PAYMENT_MODE STRING,
    PAYMENT_STATUS STRING,
    AMOUNT NUMBER(10,2),
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);

CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_DELIVERIES (
    DELIVERY_ID STRING,
    ORDER_ID STRING,
    DELIVERY_STATUS STRING,
    SHIPPED_AT TIMESTAMP_NTZ,
    DELIVERED_AT TIMESTAMP_NTZ,
    DELIVERY_PARTNER STRING,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    SOURCE_SYSTEM STRING,

    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);


CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_STATUS (
    EVENT_ID STRING,
    ORDER_ID STRING,
    PREVIOUS_STATUS STRING,
    CURRENT_STATUS STRING,
    EVENT_TIMESTAMP NUMBER,
    EVENT_SOURCE STRING,

    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);
