INSERT INTO LOGISTICS_DB.SILVER.DELIVERIES
(
    DELIVERY_ID,
    ORDER_ID,
    DELIVERY_STATUS,
    DELIVERY_PARTNER,
    SHIPPED_AT,
    DELIVERED_AT,
    CREATED_AT,
    UPDATED_AT,
    SOURCE_SYSTEM
)

SELECT
    DELIVERY_ID,
    ORDER_ID,
    DELIVERY_STATUS,
    DELIVERY_PARTNER,
    SHIPPED_AT,
    DELIVERED_AT,
    CREATED_AT,
    UPDATED_AT,
    SOURCE_SYSTEM

FROM LOGISTICS_DB.BRONZE.RAW_DELIVERIES;