INSERT INTO LOGISTICS_DB.SILVER.ORDER_STATUS_HISTORY
(
    EVENT_ID,
    ORDER_ID,
    PREVIOUS_STATUS,
    CURRENT_STATUS,
    EVENT_TIMESTAMP,
    EVENT_SOURCE
)

SELECT
    EVENT_ID,
    ORDER_ID,
    PREVIOUS_STATUS,
    CURRENT_STATUS,

    TO_TIMESTAMP_NTZ(EVENT_TIMESTAMP / 1000000000),

    EVENT_SOURCE

FROM LOGISTICS_DB.BRONZE.RAW_STATUS;