CREATE OR REPLACE TABLE LOGISTICS_DB.BRONZE.RAW_STATUS (
    EVENT_ID STRING,
    ORDER_ID STRING,
    PREVIOUS_STATUS STRING,
    CURRENT_STATUS STRING,
    EVENT_TIMESTAMP NUMBER,
    EVENT_SOURCE STRING,

    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAD_DATE DATE DEFAULT CURRENT_DATE()
);

ALTER TABLE LOGISTICS_DB.BRONZE.RAW_STATUS
ADD COLUMN SOURCE_FILE STRING;

ALTER TABLE LOGISTICS_DB.BRONZE.RAW_STATUS
ADD COLUMN FILE_ROW_NUMBER NUMBER;

ALTER TABLE LOGISTICS_DB.BRONZE.RAW_STATUS
ADD COLUMN INGESTION_PIPE STRING;